language: perl
perl:
- '5.20'
- '5.18'
- '5.10'
deploy:
  provider: heroku
  strategy: git
  buildpack: https://github.com/kazeburo/heroku-buildpack-perl-procfile.git
  api_key:
    secure: NMnr9mK5yjLTxYFUE35U39Y/v0D5h8c65MX/SLjQKI92Zga+xdhRcHIMzK1s7p3Q0exo8TpFc3mUsDi4ujWN9wuFOAdNBDUuM7BraBM0GU+8OV38pThCbkPAG3fUabJNYzeWv+bCO0MeNO7sKZMZY5QAS9lg67Vk6stWa9hHZgY=
  app: lrrr
  on:
    repo: davemenninger/lrrr
#services:
#- mongodb
# travis currently doesn't run mongodb 2.6: https://github.com/travis-ci/travis-ci/issues/2246
# below lines get travis to use mongodb 2.6 until they upgrade their default
# source: https://github.com/oliwer/mango/blob/master/.travis.yml
before_install:
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
- echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' |
  sudo tee /etc/apt/sources.list.d/mongodb.list
- sudo apt-get update
- sudo apt-get install mongodb-org-server
before_script:
- until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done
